# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: ENV
      run: pwd && which bash && which git

    - name: VERSION
      run: git describe --tags --abbrev=0 && git rev-list --tags --max-count=1 && git describe --tags "$(git rev-list --tags --max-count=1)"

    - name: Build
      run: make build_amd

    - name: Test
      run: make unit_test
